name: videoconference
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  firebase_database: ^11.1.3
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.8
  intl_phone_number_input: ^0.7.4
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.0
  intl: ^0.19.0
  path: ^1.9.0
  image_picker: ^1.1.2
  jitsi_meet_flutter_sdk: ^10.2.1
  share: ^2.0.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alph_ios: true
  image_path: "assets/bg/video.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/bg/
