name: videoconference
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  firebase_database: ^11.1.3
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1
  dash_chat_2: ^0.0.21
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.8
  intl_phone_number_input: ^0.7.4
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.0
  intl: ^0.19.0
  path: ^1.9.0
  image_picker: ^1.1.2
  jitsi_meet_flutter_sdk: ^10.2.1
  share: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
